breakout-a2c:
    env: Breakout-v4
    run: R2D2
    stop:
        episode_reward_mean: 200
        timesteps_total: 500000
    config:
        # Works for both torch and tf.
        framework: tf
        num_workers: 1
        num_gpus: 1
        lr: 0.001
        model:
          use_lstm: true