breakout-a2c:
    env: Breakout-v4
    run: A2C
    stop:
        episode_reward_mean: 500
        timesteps_total: 500000
    config:
        # Works for both torch and tf.
        framework: tf
        num_workers: 2
        num_gpus: 1
        lr: 0.001